/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriaRouteImport } from './routes/storia'
import { Route as ServiziRouteImport } from './routes/servizi'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as GioielliereBariRouteImport } from './routes/gioielliere-bari'
import { Route as GioielliSuMisuraBariRouteImport } from './routes/gioielli-su-misura-bari'
import { Route as CreaIlTuoGioielloRouteImport } from './routes/crea-il-tuo-gioiello'
import { Route as CreaAnelloPersonalizzatoBariRouteImport } from './routes/crea-anello-personalizzato-bari'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as CategorieRouteImport } from './routes/categorie'
import { Route as AtelierOrafoPugliaRouteImport } from './routes/atelier-orafo-puglia'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicFalTrellisWebhookRouteImport } from './routes/api/public/fal-trellis-webhook'

const StoriaRoute = StoriaRouteImport.update({
  id: '/storia',
  path: '/storia',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziRoute = ServiziRouteImport.update({
  id: '/servizi',
  path: '/servizi',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const GioielliereBariRoute = GioielliereBariRouteImport.update({
  id: '/gioielliere-bari',
  path: '/gioielliere-bari',
  getParentRoute: () => rootRouteImport,
} as any)
const GioielliSuMisuraBariRoute = GioielliSuMisuraBariRouteImport.update({
  id: '/gioielli-su-misura-bari',
  path: '/gioielli-su-misura-bari',
  getParentRoute: () => rootRouteImport,
} as any)
const CreaIlTuoGioielloRoute = CreaIlTuoGioielloRouteImport.update({
  id: '/crea-il-tuo-gioiello',
  path: '/crea-il-tuo-gioiello',
  getParentRoute: () => rootRouteImport,
} as any)
const CreaAnelloPersonalizzatoBariRoute =
  CreaAnelloPersonalizzatoBariRouteImport.update({
    id: '/crea-anello-personalizzato-bari',
    path: '/crea-anello-personalizzato-bari',
    getParentRoute: () => rootRouteImport,
  } as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorieRoute = CategorieRouteImport.update({
  id: '/categorie',
  path: '/categorie',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierOrafoPugliaRoute = AtelierOrafoPugliaRouteImport.update({
  id: '/atelier-orafo-puglia',
  path: '/atelier-orafo-puglia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFalTrellisWebhookRoute =
  ApiPublicFalTrellisWebhookRouteImport.update({
    id: '/api/public/fal-trellis-webhook',
    path: '/api/public/fal-trellis-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier-orafo-puglia': typeof AtelierOrafoPugliaRoute
  '/categorie': typeof CategorieRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/crea-anello-personalizzato-bari': typeof CreaAnelloPersonalizzatoBariRoute
  '/crea-il-tuo-gioiello': typeof CreaIlTuoGioielloRoute
  '/gioielli-su-misura-bari': typeof GioielliSuMisuraBariRoute
  '/gioielliere-bari': typeof GioielliereBariRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/servizi': typeof ServiziRoute
  '/storia': typeof StoriaRoute
  '/api/public/fal-trellis-webhook': typeof ApiPublicFalTrellisWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier-orafo-puglia': typeof AtelierOrafoPugliaRoute
  '/categorie': typeof CategorieRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/crea-anello-personalizzato-bari': typeof CreaAnelloPersonalizzatoBariRoute
  '/crea-il-tuo-gioiello': typeof CreaIlTuoGioielloRoute
  '/gioielli-su-misura-bari': typeof GioielliSuMisuraBariRoute
  '/gioielliere-bari': typeof GioielliereBariRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/servizi': typeof ServiziRoute
  '/storia': typeof StoriaRoute
  '/api/public/fal-trellis-webhook': typeof ApiPublicFalTrellisWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atelier-orafo-puglia': typeof AtelierOrafoPugliaRoute
  '/categorie': typeof CategorieRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/crea-anello-personalizzato-bari': typeof CreaAnelloPersonalizzatoBariRoute
  '/crea-il-tuo-gioiello': typeof CreaIlTuoGioielloRoute
  '/gioielli-su-misura-bari': typeof GioielliSuMisuraBariRoute
  '/gioielliere-bari': typeof GioielliereBariRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/servizi': typeof ServiziRoute
  '/storia': typeof StoriaRoute
  '/api/public/fal-trellis-webhook': typeof ApiPublicFalTrellisWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atelier-orafo-puglia'
    | '/categorie'
    | '/contatti'
    | '/cookie-policy'
    | '/crea-anello-personalizzato-bari'
    | '/crea-il-tuo-gioiello'
    | '/gioielli-su-misura-bari'
    | '/gioielliere-bari'
    | '/privacy-policy'
    | '/servizi'
    | '/storia'
    | '/api/public/fal-trellis-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atelier-orafo-puglia'
    | '/categorie'
    | '/contatti'
    | '/cookie-policy'
    | '/crea-anello-personalizzato-bari'
    | '/crea-il-tuo-gioiello'
    | '/gioielli-su-misura-bari'
    | '/gioielliere-bari'
    | '/privacy-policy'
    | '/servizi'
    | '/storia'
    | '/api/public/fal-trellis-webhook'
  id:
    | '__root__'
    | '/'
    | '/atelier-orafo-puglia'
    | '/categorie'
    | '/contatti'
    | '/cookie-policy'
    | '/crea-anello-personalizzato-bari'
    | '/crea-il-tuo-gioiello'
    | '/gioielli-su-misura-bari'
    | '/gioielliere-bari'
    | '/privacy-policy'
    | '/servizi'
    | '/storia'
    | '/api/public/fal-trellis-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtelierOrafoPugliaRoute: typeof AtelierOrafoPugliaRoute
  CategorieRoute: typeof CategorieRoute
  ContattiRoute: typeof ContattiRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  CreaAnelloPersonalizzatoBariRoute: typeof CreaAnelloPersonalizzatoBariRoute
  CreaIlTuoGioielloRoute: typeof CreaIlTuoGioielloRoute
  GioielliSuMisuraBariRoute: typeof GioielliSuMisuraBariRoute
  GioielliereBariRoute: typeof GioielliereBariRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServiziRoute: typeof ServiziRoute
  StoriaRoute: typeof StoriaRoute
  ApiPublicFalTrellisWebhookRoute: typeof ApiPublicFalTrellisWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storia': {
      id: '/storia'
      path: '/storia'
      fullPath: '/storia'
      preLoaderRoute: typeof StoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi': {
      id: '/servizi'
      path: '/servizi'
      fullPath: '/servizi'
      preLoaderRoute: typeof ServiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioielliere-bari': {
      id: '/gioielliere-bari'
      path: '/gioielliere-bari'
      fullPath: '/gioielliere-bari'
      preLoaderRoute: typeof GioielliereBariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioielli-su-misura-bari': {
      id: '/gioielli-su-misura-bari'
      path: '/gioielli-su-misura-bari'
      fullPath: '/gioielli-su-misura-bari'
      preLoaderRoute: typeof GioielliSuMisuraBariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crea-il-tuo-gioiello': {
      id: '/crea-il-tuo-gioiello'
      path: '/crea-il-tuo-gioiello'
      fullPath: '/crea-il-tuo-gioiello'
      preLoaderRoute: typeof CreaIlTuoGioielloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crea-anello-personalizzato-bari': {
      id: '/crea-anello-personalizzato-bari'
      path: '/crea-anello-personalizzato-bari'
      fullPath: '/crea-anello-personalizzato-bari'
      preLoaderRoute: typeof CreaAnelloPersonalizzatoBariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorie': {
      id: '/categorie'
      path: '/categorie'
      fullPath: '/categorie'
      preLoaderRoute: typeof CategorieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier-orafo-puglia': {
      id: '/atelier-orafo-puglia'
      path: '/atelier-orafo-puglia'
      fullPath: '/atelier-orafo-puglia'
      preLoaderRoute: typeof AtelierOrafoPugliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fal-trellis-webhook': {
      id: '/api/public/fal-trellis-webhook'
      path: '/api/public/fal-trellis-webhook'
      fullPath: '/api/public/fal-trellis-webhook'
      preLoaderRoute: typeof ApiPublicFalTrellisWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtelierOrafoPugliaRoute: AtelierOrafoPugliaRoute,
  CategorieRoute: CategorieRoute,
  ContattiRoute: ContattiRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  CreaAnelloPersonalizzatoBariRoute: CreaAnelloPersonalizzatoBariRoute,
  CreaIlTuoGioielloRoute: CreaIlTuoGioielloRoute,
  GioielliSuMisuraBariRoute: GioielliSuMisuraBariRoute,
  GioielliereBariRoute: GioielliereBariRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServiziRoute: ServiziRoute,
  StoriaRoute: StoriaRoute,
  ApiPublicFalTrellisWebhookRoute: ApiPublicFalTrellisWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
