// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyhvdxqwdtajuwbfrywc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95aHZkeHF3ZHRhanV3YmZyeXdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAwOTM1NjEsImV4cCI6MjA5NTY2OTU2MX0.whKuM_Vj-O9pVXOm8ds_KnuqEGQ8zhkkm-h_d0mlj4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});